### ISSUE TITLE
Problem using tikzDevice with knitr (Windows)

### ISSUE THREAD

**Issue by indridiindridason** [yihui/tikzDevice#99]
(Also reported at http://tex.stackexchange.com/q/222156/9128)

I can't seem to get knitr to work with tikzdevice (using Rstudio on Windows).  The problems seems to be related to spaces in, I'm guessing, the path to tikz. A simple example:

```\
documentclass{article}
\usepackage{dcolumn}
\usepackage{tikz}
\usepackage{amsmath}
\usepackage{amsfonts}

\begin{document} 
<<test, dev='tikz'>>=
library(knitr)
library(tikzDevice)
library(ggplot2) 
plot(1) 
@ 
\end{document} 
```
produces:

```
   Quitting from lines 4-5 (testets.Rnw) 
   Error in system(latexCmd, intern = T, ignore.stderr = T) : 
   'C:\Program' not found
   Calls: knit ... print.recordedplot -> replayPlot -> <Anonymous> -> getMetricsFromLatex
```

It seems clear to me that there is a problem with the path including spaces - my LaTeX installation is under "C:\Program Files\" but I'm at a loss as how to fix that short of re-installing Latex. For what it is worth, knitr works fine as long as I don't call tikzDevice and MikTeX + tikz works fine outside of knitr.

sessionInfo() produces:

```
R version 3.1.2 (2014-10-31)
Platform: x86_64-w64-mingw32/x64 (64-bit)

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] ggplot2_1.0.0    tikzDevice_0.8.1 knitr_1.8       

loaded via a namespace (and not attached):
[1] colorspace_1.2-4 digest_0.6.8     evaluate_0.5.5   filehash_2.2-2   formatR_1.0      grid_3.1.2       gtable_0.1.2    
[8] labeling_0.3     MASS_7.3-35      munsell_0.4.2    plyr_1.8.1       proto_0.3-10     Rcpp_0.11.3      reshape2_1.4.1  
[15] scales_0.2.4     stringr_0.6.2    tools_3.1.2 
```

**Comment by indridiindridason** [comment]
Yes, I had the exact same problem before updating to 0.8.1.

**Comment by krlmlr** [comment]
It looks like the error originates [in this code](https://github.com/yihui/tikzDevice/blob/6813a07614c6c42b4fad796ce85cb5ffaef9d97a/R/latexStrWidth.R#L409). This should be solvable by either double-quoting the path to `pdflatex` et al., or by using `system2()` instead of `system()` (with a different API). Would you like to contribute a pull request?

**Comment by indridiindridason** [comment]
Thanks - I'm pretty new to R but I'll poke around and see if I can figure it out and, if so, I'll submit a pull request.

**Comment by krlmlr** [comment]
@indridiindridason: Any news on this issue?

**Comment by yihui** [comment]
Since this issue seems to have affected multiple users, and the fix should be simple, I just pushed a fix in the `bugfix/quote-path` branch (46339ad). Please test it by installing this version:

```r
devtools::install_github('yihui/tikzDevice@bugfix/quote-path')
```

Note you may need to install [RTools](http://cran.rstudio.com/bin/windows/Rtools/).

**Comment by indridiindridason** [comment]
I'm not sure I'm testing this correctly but this was my R chunk:

    <<dev="tikz", sanitize=TRUE>>=
      sessionInfo()
      library(knitr)
      library(ggplot2)
      library(Rtools)
      devtools::install_github('yihui/tikzDevice@bugfix/quote-path')
      library(tikzDevice)
      sessionInfo()
      qplot(1:10, 1:10)
    @  

and it seems the problem remains - this was the result:

    * installing *source* package 'tikzDevice' ...
    ** libs

    *** arch - i386
    gcc -m32 -I"C:/R-3.1.2/include" -DNDEBUG     -I"d:/RCompile/CRANpkg/extralibs64/local/include"     -O3 -Wall  -std=gnu99 -mtune=core2 -c tikzDevice.c -o tikzDevice.o
    gcc -m32 -shared -s -static-libgcc -o tikzDevice.dll tmp.def tikzDevice.o -Ld:/RCompile/CRANpkg/extralibs64/local/lib/i386 -Ld:/RCompile/CRANpkg/extralibs64/local/lib -LC:/R-3.1.2/bin/i386 -lR
    installing to C:/Users/Indridi/Documents/R/win-library/3.1/tikzDevice/libs/i386

    *** arch - x64
    gcc -m64 -I"C:/R-3.1.2/include" -DNDEBUG     -I"d:/RCompile/CRANpkg/extralibs64/local/include"     -O2 -Wall  -std=gnu99 -mtune=core2 -c tikzDevice.c -o tikzDevice.o
    gcc -m64 -shared -s -static-libgcc -o tikzDevice.dll tmp.def tikzDevice.o -    Ld:/RCompile/CRANpkg/extralibs64/local/lib/x64 -Ld:/RCompile/CRANpkg/extralibs64/local/lib -LC:/R-3.1.2/bin/x64 -lR
    installing to C:/Users/Indridi/Documents/R/win-library/3.1/tikzDevice/libs/x64
    ** R
    ** inst
    ** tests
    ** preparing package for lazy loading
    ** help
    *** installing help indices
    ** building package indices
    ** installing vignettes
    ** testing if installed package can be loaded
    *** arch - i386
    *** arch - x64
    * DONE (tikzDevice)
    Using TikZ metrics dictionary at:
	vsimple-tikzDictionary
    Quitting from lines 12-20 (vsimple.Rnw) 
    Error in system(latexCmd, intern = T, ignore.stderr = T) : 
      'C:\Program' not found
    Calls: knit ... widthDetails.text -> grid.Call -> <Anonymous> -> getMetricsFromLatex

    Execution halted

**Comment by yihui** [comment]
Yes, you were testing it correctly, and it was just me making a stupid mistake. Please reinstall that branch and test again. Thanks!

**Comment by indridiindridason** [comment]
Tried it again and now I get this:

    Using TikZ metrics dictionary at:
	vsimple-tikzDictionary
    Quitting from lines 12-20 (vsimple.Rnw) 
    Error in createLockFile(lockname) : cannot create lock file
    Calls: knit ... evalWithoutInterrupts -> .Call -> dbFetch -> dbFetch -> createLockFile

**Comment by yihui** [comment]
@indridiindridason I guess you need to delete the files under the directory of vsimple.Rnw that have `vsimple-tikzDictionary` in the filenames. Or just delete everything except the source files.

**Comment by indridiindridason** [comment]
@yihui Yes, that seems to work - fantastic. Before I tried that, I found this:

    devtools::install_github("rdpeng/filehash@next")

from https://github.com/Sharpie/RTikZDevice/issues/66, which also seems to solve the problem.  Thanks for looking into this and apologies for not having found the time to try to figure it out myself earlier.

**Comment by yihui** [comment]
@indridiindridason Glad to know that. Thanks for helping test the fix!
